name:                analytics
version:             0.1.0.0
github:              "adamwespiser/analytics"
license:             BSD3
author:              "Adam Wespiser"
maintainer:          "adamwespiser@gmail.com"
copyright:           "Copyright (c) 2019 Adam Wespiser"

default-extensions:
- OverloadedStrings


extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/adamwespiser/analytics#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  analytics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - analytics

  analytics-migrations:
    main:                db/Migrations.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - analytics
    - postgresql-simple >= 0.6.2
    - postgresql-simple-migration >= 0.1.14.0
    - bytestring >= 0.10.8.2



tests:
  analytics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - analytics
