name:                analytics
version:             0.1.0.1
license:             BSD3
license-file:        LICENSE
category:            Web
author:              "Adam Wespiser"
maintainer:          "adamwespiser@gmail.com"
copyright:           "© 2020 Adam Wespiser"
github:              https://github.com/adamwespiser/analytics

extra-source-files:
- README.md
- ChangeLog.md
- LICENSE
- Procfile

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wtype-defaults

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- NoMonomorphismRestriction
- OverloadedLabels
- OverloadedStrings
- PartialTypeSignatures
- PatternSynonyms
- StandaloneDeriving
- RecordWildCards
- RankNTypes
- ScopedTypeVariables
- TypeOperators
- TypeApplications
- TypeFamilies

dependencies:
- base >= 4.7
- aeson >= 1.4.5.0
- bytestring >= 0.10.8.2
- exceptions
- generics-sop
- http-client
- http-types
- postgresql-simple
- extra >= 1.6.18
- mtl >= 2.2.2
- safe >= 0.3.17
- servant >= 0.16.2
- servant-client
- servant-server
- servant-options >= 0.1.0.0
- squeal-postgresql
- text >= 1.2.3.1
- time >= 1.8.0.2
- transformers >= 0.5.6.2
- uuid-types >= 1.0.3
- wai >= 3.2.2.1
- wai-cors >= 0.2.7
- wai-extra >= 3.0.28
- warp >= 3.2.28

library:
  source-dirs: src

executables:
  analytics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - analytics
    - squeal-postgresql

  analytics-migrations:
    main:                db/Migrations.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - analytics

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N1
    dependencies:
    - analytics
    - hspec >= 2.7.1
    - hspec-core
    - postgres-options >= 0.1.0.1
    - postgresql-simple >= 0.4.9.0
    - persistent >= 2.5
    - protolude >= 0.2
    - string-conversions >= 0.4.0.1
    - tmp-postgres >= 0.3.0.1
